name: 'Branch Policy'
description: 'This action validates the branch name complaince to RAC branching policy'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
    
runs:
  using: "composite"
  steps:
    - run: write-output "Hello ${{ inputs.who-to-greet }}"
      shell: pwsh
    - id: random-number-generator
      run: write-output "::set-output name=random-number::$(Get-Random)"
      shell: pwsh