name: 'Branch Policy'
description: 'This action validates the branch name complaince to RAC branching policy'

inputs:
  branch-name:  # id of input
    description: 'branch name'
    required: true
    default: 'World'

outputs:
  branch-validation:
    description: "Branch validation output"
    value: ${{ steps.validate-branch-name.outputs.branch-validation }}
    
runs:
  using: "composite"
  steps:
    - id: validate-branch-name
      shell: pwsh
      run: |
        $branch = "${{ inputs.branch-name }}"
        write-output "Applying branching policy on $branch"
        $result =  $branch -match "([a-z])+\/+([A-Z]{2,4}\-\d{2,5})+(\w)+"
        $result
        write-output "Result $result"

        if($result -eq $true){
          write-output "::set-output name=branch-validation::Success"
        }
        else{
          write-output "::set-output name=branch-validation::Failed"
        }
        
      